// src/routes/contact/+page.svelte
<script lang="ts">
  import { ExternalLink } from '~/components';
</script>

<svelte:head>
  <title>連絡先 | Kodai のウェブサイト</title>
</svelte:head>

<h1>連絡先</h1>
<ul>
  <li>
    <a href="mailto:nobita.0918@gmail.com">Gmail</a>
  </li>
  <li>
    X (Twitter)：
    <ExternalLink url="https://twitter.com/0918nobita" label="@0918nobita" />
  </li>
  <li>
    Bluesky：
    <ExternalLink
      url="https://bsky.app/profile/kodai.engineer"
      label="@kodai.engineer"
    />
  </li>
</ul>

// app/pages/contact.vue
<script setup lang="ts">
useHead({
  title: '連絡先 | Kodai のウェブサイト',
});
</script>

<template>
  <h2>{{ $t('連絡先') }}</h2>

  <ul>
    <li>Gmail：<a href="mailto:nobita.0918@gmail.com">nobita.0918@gmail.com</a></li>

    <li>
      X (Twitter)：<a href="https://x.com/0918nobita" target="_blank" rel="noopener noreferrer"
        >@0918nobita</a
      >
    </li>
  </ul>
</template>

<style scoped>
h2 {
  margin: 0;
}

ul {
  margin: 0;
}
</style>
